/* Ruben Castro Espinoza 
CSE2 Friday october 30th 
This program will ask the user for 5 diffrent input names. It will then print back the five names in order 
with a random rumber from 1 to 100 next to each inputed name. This program will use scanner math.random and 
arrays to acomplish this task.*/
import java.util.Scanner; // informs the program that the user will type in information in the future 
public class Arrays{// 
 public static void main(String[]args){
  int x= (int)(Math.random()*5+6); // this variable is randomly generated by math.randow it determines the # of names asked by the program
  System.out.println("please enter "+ x +" names ");
  Scanner myScanner= new Scanner(System.in);//creates variable to store future user inputed information. 
  int numberofNames=x;// sets random number equal to number of names variable.
  String []students= new String[numberofNames];// creates array and allocates it.
   for (int i=0 ; i<numberofNames; i++){// for loop that is initializing the students array
    students[i]= myScanner.nextLine();
    }
  int []midterm= new int [numberofNames];//creates midterm array and allocates it. 
    for(int j=0; j<numberofNames; j++){// for loop that is initializing midterm array.
     midterm[j]=(int)(Math.random()*100+1);// creates randomly genertated number between 1 and 100 that is initialized into the array 
     }
    for (int y=0; y<numberofNames;y++){// for loop that prints out each arrays' members and its initialized value 
     System.out.println (students[y] +":" +midterm[y]);
    }
 
 }
}
  